/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        white: "var(--color-white)",
        black: "var(--color-black)",
        background: "var(--color-background)",
        "background-dark": "var(--color-background-dark)",
        "neutral-50": "var(--color-neutral-50)",
        "neutral-100": "var(--color-neutral-100)",
        "neutral-200": "var(--color-neutral-200)",
        "neutral-300": "var(--color-neutral-300)",
        "neutral-400": "var(--color-neutral-400)",
        "neutral-500": "var(--color-neutral-500)",
        "neutral-600": "var(--color-neutral-600)",
        "neutral-700": "var(--color-neutral-700)",
        "neutral-800": "var(--color-neutral-800)",
        "neutral-900": "var(--color-neutral-900)",
        "primary-50": "var(--color-primary-50)",
        "primary-100": "var(--color-primary-100)",
        "primary-200": "var(--color-primary-200)",
        "primary-300": "var(--color-primary-300)",
        "primary-400": "var(--color-primary-400)",
        "primary-500": "var(--color-primary-500)",
        "primary-600": "var(--color-primary-600)",
        "primary-700": "var(--color-primary-700)",
        "primary-800": "var(--color-primary-800)",
        "primary-900": "var(--color-primary-900)",
        danger: "var(--color-danger)",
        success: "var(--color-success)",
        warning: "var(--color-warning)",
        complementary: "var(--color-complementary)",
        "dark-bg": "var(--color-dark-bg)",
      },
    },
    fontFamily: {
      Poppinsextralight: ["Poppinsextralight"],
      Poppinslight: ["Poppinslight"],
      Poppinsregular: ["Poppinsregular"],
      Poppinsmedium: ["Poppinsmedium"],
      Poppinsbold: ["Poppinsbold"],
      Tajawalextralight: ["Tajawalextralight"],
      Tajawallight: ["Tajawallight"],
      Tajawalregular: ["Tajawalregular"],
      Tajawalmedium: ["Tajawalmedium"],
      Tajawalbold: ["Tajawalbold"],
    },
  },
  plugins: [],
};
