
auth.token=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

defaults.org=shop-simplist
defaults.project=react-native

defaults.url=https://sentry.io/
